# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaixaHoraria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, null=True)),
                ('horaI', models.DateTimeField(null=True)),
                ('horaF', models.DateTimeField(null=True)),
                ('horaI2', models.DateTimeField(null=True)),
                ('horaF2', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, verbose_name='Consistente')),
                ('justificativa', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, null=True)),
                ('chefe', models.CharField(max_length=300, null=True)),
                ('faixaHr', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frequencia.FaixaHoraria')),
            ],
        ),
    ]
