# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frequencia', '0002_auto_20171113_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequencia',
            name='dia',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='horaRegistro',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='ip',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='frequencia',
            name='tipo',
            field=models.BooleanField(default=False, verbose_name='Entrada'),
        ),
    ]
